### ISSUE TITLE
Unbind Broken

### ISSUE THREAD

**Issue by tommyday** [BIG-RAT/mobile_to_local#11]
Using the "-unbind" true" switch, computer stays bound to AD and the log states "no change to current bind status will be performed"

**Comment by BIG-RAT** [comment]
What is the full command used? I used the following:
`"/Users/Shared/Mobile to Local.app/Contents/MacOS/Mobile to Local" -allowNewUsername false -userType admin -mode silent -unbind true`

A little snip-it form the log:
```
Tue Apr 30 12:25:01 M1ni tester[migrate]: Home directory will not be renamed
Tue Apr 30 12:25:01 M1ni tester[migrate]: User will be migrated as an admin user
Tue Apr 30 12:25:01 M1ni tester[migrate]: machine will be unbound from Active Directory
Tue Apr 30 12:25:01 M1ni tester[migrate]: tester is a FileVault enabled user
Tue Apr 30 12:25:01 M1ni tester[migrate]: performing machine unbind
Tue Apr 30 12:25:01 M1ni tester[migrate]: result of unbind operation: 0
```

**Comment by tommyday** [comment]
I am using /private/tmp/Mobile\ to\ Local.app/Contents/MacOS/Mobile\ to\ Local -unbind true

**Comment by BIG-RAT** [comment]
Thanks for the quick reply and details. Believe I found the issue.
As time permits, let me know if v2.6.1 does the job.

**Comment by tommyday** [comment]
Thanks for that update, I am happy to report the unbind with 2.6.1 works properly!

**Comment by BIG-RAT** [comment]
Thanks for the update.
