### ISSUE TITLE
Can not add a user password

### ISSUE THREAD

**Issue by ateazzie** [BIG-RAT/mobile_to_local#3]
Hi

thnx for this great piece of software which we will use for our migration
When I started the program I was not able to add my user password, no characters appeared in the field

Pls advice

**Comment by BIG-RAT** [comment]
How is the app being lauched?  If you launch it from Terminal (say the app is in /Users/Shared):

sudo /Users/Shared/Mobile\ to\ Local.app/Contents/MacOS/Mobile\ to\ Local ?


Does it behave any differently?

________________________________

**Comment by ateazzie** [comment]
Hi

Thnx for coming back to me
It is in downloads and launched via terminal

Thnx

**Comment by ateazzie** [comment]
small addition
when I want to add the users password, it appears in the terminal, not in the app

**Comment by BIG-RAT** [comment]
Shows up in Terminal as plain text?  Wonder if launching it as follows makes any difference and are you able to change the username?


currentUser=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' );sudo launchctl asuser "$currentUser" /Users/"$currentUser"/Downloads/Mobile\ to\ Local.app/Contents/MacOS/Mobile\ to\ Local -allowNewUsername true


________________________________

**Comment by ateazzie** [comment]
Hi
this worked. Brilliant!
do I have to add this in my deployment?

We will migrate over 1100 Macs, where this is the major part

thnx

**Comment by BIG-RAT** [comment]
?Sure.  Depending on how you want things to run add the script as a post install script as part of the package.

________________________________

**Comment by ateazzie** [comment]
do you have any idea why the application will not run with out adding allowNewUsername true?

**Comment by BIG-RAT** [comment]
I do not.  Will it run if you run with allowNewUsername false?
