### ISSUE TITLE
Strange Behavior During Password Change

### ISSUE THREAD

**Issue by charlespineda** [BIG-RAT/mobile_to_local#7]
The Tool works great, I did notice during my testing that when the user wants to change their local password when they put in their current password and then x2 new passwords the "Red" text reads "Invalid Password" and then disappears but it does change the password. However, a non novice user might think it did not work and try to change it again thinking it didn't work and change it yet again.  During my testing I got completely locked out of the machine and the profile when booting into recovery is still not recognized as being local so I was unable to change the password even via recovery and the machine was hosed.

**Comment by BIG-RAT** [comment]
Haven't been able to replicate the behavior.  Don't know if it's a factor, is this happening on both Intel and Apple Silicon machines?  What OS?
